---
services:
  videodock:
    image: bear0328/videodock:latest
    container_name: videodock
    ports:
      - "8620:8620"
    volumes:
      - /mnt/user/media/ori/91:/adult
      - /mnt/user/downloads/youtube:/general
      - /mnt/user/appdata/videodock/data:/appdata
    environment:
      - VIDEODB_DATA=/
      - APPDATA=/appdata
      - PAGE_PROXY=http://192.168.6.111:7890
    restart: unless-stopped
